// ===========================================================================
// RUNTIME
// ===========================================================================

testing.test("R: extend.isString")
	testing.asFalse(extend.isString([]))
	testing.asFalse(extend.isString([1,2,3,4]))
	testing.asFalse(extend.isString(1))
	testing.asTrue(extend.isString(""))
	testing.asTrue(extend.isString("hello"))
	testing.asTrue(extend.isString("1"))
	testing.asFalse(extend.isString({}))
	testing.asFalse(extend.isString({0:0,1:1,2:2}))
	testing.asFalse(extend.isString(true))
	testing.asFalse(extend.isString(false))
	testing.asFalse(extend.isString(null))
	testing.asFalse(extend.isString(undefined))
testing.end()

testing.test("R: extend.isList")
	testing.asTrue(extend.isList([]))
	testing.asTrue(extend.isList([1,2,3,4]))
	testing.asFalse(extend.isList(1))
	testing.asFalse(extend.isList(""))
	testing.asFalse(extend.isList("hello"))
	testing.asFalse(extend.isList("1"))
	testing.asFalse(extend.isList({}))
	testing.asFalse(extend.isList({0:0,1:1,2:2}))
	testing.asFalse(extend.isList(true))
	testing.asFalse(extend.isList(false))
	testing.asFalse(extend.isList(null))
	testing.asFalse(extend.isList(undefined))
testing.end()

testing.test("R: extend.isMap")
	testing.asFalse(extend.isMap([]))
	testing.asFalse(extend.isMap([1,2,3,4]))
	testing.asFalse(extend.isMap(1))
	testing.asFalse(extend.isMap(""))
	testing.asFalse(extend.isMap("hello"))
	testing.asFalse(extend.isMap("1"))
	testing.asTrue(extend.isMap({}))
	testing.asTrue(extend.isMap({0:0,1:1,2:2}))
	testing.asFalse(extend.isMap(true))
	testing.asFalse(extend.isMap(false))
	testing.asFalse(extend.isMap(null))
	testing.asFalse(extend.isMap(undefined))
testing.end()

testing.test("R: extend.slice for strings")
	testing.same(extend.slice(""), "")
	testing.same(extend.slice("hello"), "hello")
	testing.same(extend.slice("hello", 0),    "hello")
	testing.same(extend.slice("hello", 0, 1), "h")
	testing.same(extend.slice("hello", 0, 2), "he")
	testing.same(extend.slice("hello", 1, 2), "e")
	testing.same(extend.slice("hello", 0, 5), "hello")
	testing.same(extend.slice("hello", -1),    "o")
	testing.same(extend.slice("hello", -2),    "lo")
	testing.same(extend.slice("hello", -2, -1),"l")
	testing.same(extend.slice("hello", -2, 5),"lo")
testing.end()

testing.test("R: extend.createMapFromItems")
	testing.same(extend.createMapFromItems(), {})
	testing.same(extend.createMapFromItems(["a",1]), {a:1})
	testing.same(extend.createMapFromItems(["a",1],["b",2]),{a:1,b:2})
testing.end()

testing.test("R: extend.isIn")
	testing.asTrue(extend.isIn(0,[0]))
	testing.asTrue(extend.isIn(0,[1,0]))
	testing.asTrue(extend.isIn(0,[1,0,0]))
	testing.asFalse(extend.isIn(9,[1,0,0]))
testing.end()

testing.test("R: extend.difference")
	testing.same(extend.difference(null, null)  , null)
	testing.same(extend.difference([], null)    , [])
	testing.same(extend.difference([], [])      , [])
	testing.same(extend.difference([1,2,3], []) , [1,2,3])
testing.end()

// END
