// ===========================================================================
// RUNTIME
// ===========================================================================

Testing.test("R: Extend.isString")
	Testing.asFalse(Extend.isString([]))
	Testing.asFalse(Extend.isString([1,2,3,4]))
	Testing.asFalse(Extend.isString(1))
	Testing.asTrue(Extend.isString(""))
	Testing.asTrue(Extend.isString("hello"))
	Testing.asTrue(Extend.isString("1"))
	Testing.asFalse(Extend.isString({}))
	Testing.asFalse(Extend.isString({0:0,1:1,2:2}))
	Testing.asFalse(Extend.isString(true))
	Testing.asFalse(Extend.isString(false))
	Testing.asFalse(Extend.isString(null))
	Testing.asFalse(Extend.isString(undefined))
Testing.end()

Testing.test("R: Extend.isList")
	Testing.asTrue(Extend.isList([]))
	Testing.asTrue(Extend.isList([1,2,3,4]))
	Testing.asFalse(Extend.isList(1))
	Testing.asFalse(Extend.isList(""))
	Testing.asFalse(Extend.isList("hello"))
	Testing.asFalse(Extend.isList("1"))
	Testing.asFalse(Extend.isList({}))
	Testing.asFalse(Extend.isList({0:0,1:1,2:2}))
	Testing.asFalse(Extend.isList(true))
	Testing.asFalse(Extend.isList(false))
	Testing.asFalse(Extend.isList(null))
	Testing.asFalse(Extend.isList(undefined))
Testing.end()

Testing.test("R: Extend.isMap")
	Testing.asFalse(Extend.isMap([]))
	Testing.asFalse(Extend.isMap([1,2,3,4]))
	Testing.asFalse(Extend.isMap(1))
	Testing.asFalse(Extend.isMap(""))
	Testing.asFalse(Extend.isMap("hello"))
	Testing.asFalse(Extend.isMap("1"))
	Testing.asTrue(Extend.isMap({}))
	Testing.asTrue(Extend.isMap({0:0,1:1,2:2}))
	Testing.asFalse(Extend.isMap(true))
	Testing.asFalse(Extend.isMap(false))
	Testing.asFalse(Extend.isMap(null))
	Testing.asFalse(Extend.isMap(undefined))
Testing.end()

Testing.test("R: Extend.slice for strings")
	Testing.same(Extend.slice(""), "")
	Testing.same(Extend.slice("hello"), "hello")
	Testing.same(Extend.slice("hello", 0),    "hello")
	Testing.same(Extend.slice("hello", 0, 1), "h")
	Testing.same(Extend.slice("hello", 0, 2), "he")
	Testing.same(Extend.slice("hello", 1, 2), "e")
	Testing.same(Extend.slice("hello", 0, 5), "hello")
	Testing.same(Extend.slice("hello", -1),    "o")
	Testing.same(Extend.slice("hello", -2),    "lo")
	Testing.same(Extend.slice("hello", -2, -1),"l")
	Testing.same(Extend.slice("hello", -2, 5),"lo")
Testing.end()

Testing.test("R: Extend.createMapFromItems")
	Testing.same(Extend.createMapFromItems(), {})
	Testing.same(Extend.createMapFromItems(["a",1]), {a:1})
	Testing.same(Extend.createMapFromItems(["a",1],["b",2]),{a:1,b:2})
Testing.end()

Testing.test("R: Extend.isIn")
	Testing.asTrue(Extend.isIn(0,[0]))
	Testing.asTrue(Extend.isIn(0,[1,0]))
	Testing.asTrue(Extend.isIn(0,[1,0,0]))
	Testing.asFalse(Extend.isIn(9,[1,0,0]))
Testing.end()

// END
